name: 'Quick Checks: pull requests'

on:
  # We only run checks on pull request events:
  # - If there are changes outside the ignored, non-code paths below
  pull_request:
    types:
      - opened
      - ready_for_review
      - reopened
      - synchronize
    paths-ignore:
      - 'CHANGELOG.md'
      - '.changes/**'
      - 'version/VERSION'
      - 'docs/**'

# This workflow runs for not-yet-reviewed external contributions and so it
# intentionally has no write access and only limited read access to the
# repository.
permissions:
  contents: read

jobs:
 quick-checks:
  uses: ./.github/workflows/checks.yml